import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
import DashboardPage from './dashboard'
import { GetServerSidePropsContext } from 'next'
import { checkAuth } from '@/utils/checkAuth'
import { FileItem } from '@/api/dto/files.dto'
import * as Api from '@/api'

interface Props {
  items: FileItem[]
}

export default function Home({items}: Props) {
  return (
    <>
      <Head>
        <title>Cloud Storage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <DashboardPage items={items} />
      </main>
    </>
  )
}

export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
  const authProps = await checkAuth(ctx)

  if('redirect' in authProps) {
      return authProps
  }
  
  try {
    const items = await Api.files.getAll()
    return {
        props: { items }
    }
    } catch (err) {
        return {
            props: { items: [] }
        }
    }
} 
